name-template: '$NEXT_PATCH_VERSIONv'
tag-template: '$NEXT_PATCH_VERSIONv'

categories:
  - title: '🚀 New Features'
    labels:
      - 'type:features'
  - title: '🐞 Bugs Fixes'
    labels:
      - 'type:fix'
  - title: '📚 Documentation'
    labels:
      - 'type:documentation'
  - title: '🛠 Configuration'
    labels:
      - 'type:config'
      - 'type:build'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES