name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'type:features'
  - title: '🐞 Bugs Fixes'
    labels:
      - 'type:fix'
  - title: '📚 Documentation'
    labels:
      - 'type:documentation'
  - title: '🛠 Configuration'
    labels:
      - 'type:config'
      - 'type:build'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: 'type:build'
    files:
      - ".github/**"
      - "pom.xml"
      - ".travis.yml"
      - ".gitignore"
      - "Dockerfile"
      - ".codecov.yml"
  - label: 'type:features'
    files:
      - "src/main/*"
    branch:
      - '/feature\/.+/'
  - label: 'type:fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'type:tests'
    files:
      - "src/test/*"
  - label: 'type:documentation'
    files:
      - '*.md'
      - "docs/**"
  - label: "type:trash"
    files:
      - ".idea/**"
      - "target/**"