name: Check and add labels in PR

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  label-verify:
    runs-on: ubuntu-20.04
    outputs:
      result: ${{ steps.check-labels.outputs.result }}
    uses: ./.github/workflows/label-verify.yml
    with:
      exit_type: ${{ github.event.action == 'opened' && 'success' || 'failure' }}
  labeler:
    if: needs.label-verify.outputs.result == 'failure'
    runs-on: ubuntu-20.04
    needs: label-verify
    uses: ./.github/workflows/labeler.yml
  retry-label-verify:
    runs-on: ubuntu-20.04
    needs: labeler
    uses: ./.github/workflows/label-verify.yml