name: Verify labels in PR

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  label-verify:
    runs-on: ubuntu-20.04
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "type:fix, type:features, type:documentation, type:tests, type:config, type:build"
  labeler:
    runs-on: ubuntu-20.04
    needs: label-verify
    steps:
      - uses: ./.github/workflows/labeler.yml
        if: needs.label-verify.outputs.status == 'failure'