name: Verify labels in PR

on:
  pull_request:
    types: [ labeled, unlabeled, synchronize ]
  workflow_call:

jobs:
  label-verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "type:fix, type:features, type:documentation, type:tests, type:config, type:build"