name: "Verify labels in PR"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-verify:
    needs: pr-labeler
    runs-on: ubuntu-20.04
    steps:
      - uses: zwaldowski/match-label-action@v4
        with:
          allowed: 'type:fix, type:features, type:documentation, type:tests, type:config, type:build'