name: Auto-assign themes to PR

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  file-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/file-labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  branch-labeler:
    needs: file-labeler
    runs-on: ubuntu-20.04
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: ./.github/branch-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label-verify:
    uses: .github/workflows/label-verify.yml