name: Verify labels in PR

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
  workflow_call:

jobs:
  label-verify:
    runs-on: ubuntu-20.04
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - id: check-labels
        uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "type:fix, type:features, type:documentation, type:tests, type:config, type:build"
#         Ignore the error when the opened event.
          exit_type: ${{ github.event.action == 'opened' && !github.event_name='workflow_call' && 'success' || 'failure' }}
  labeler:
    runs-on: ubuntu-20.04
    needs: label-verify
    steps:
      - uses: actions/checkout@v3
#       If label-verify is not passed, then we launch the labeler.
      - if: needs.label-verify.outputs.status == 'failure'
        uses: ./.github/workflows/labeler.yml