name: Release Draft

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  update-draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}