name: Release Draft

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}